language: python
python:
  - "3.6"
install:
  - pip install -r api/v1/requirements.txt
script:
  - nosetests nosetests api/v1/tests.py
branches:
  only:
  - master
  - develop
  - feature/apiv1_branch
after_success:
- coveralls
